#! /bin/bash

set -e

source autonice-common

function stop-autonice {
    set-partition-variables "$1"
    echo -n "stopping my autonice on $PARTITION: "
    if pkill -f "$PGREP_PATTERN"; then
        echo "done"
    else
        echo "no match"
    fi
}

for PARTITION in $PARTITIONS; do
    stop-autonice $PARTITION
done
