#! /bin/bash

set -e

source autonice-common

function check-autonice {
    set-partition-variables "$1"
    echo -n "check if my autonice is running on $PARTITION: "
    if pgrep -f "$PGREP_PATTERN" > /dev/null; then
        echo "yes"
    else
        echo "no"
    fi
}

for PARTITION in $PARTITIONS; do
    check-autonice $PARTITION
done
